# Generated by Django 4.2.4 on 2023-09-10 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userfollowing_userfollowing_unique_followers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
